name: Deploy and Validate Metadata

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  sfdxvalidate:
    name: "Run SFDX Validate"
    runs-on: ubuntu-latest
    container:
      image: salesforce/cli:latest-slim

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install sfdx-git-delta plugin
        run: echo "y" | sf plugins install sfdx-git-delta

      - name: 'Authentification Salesforce'
        run: echo ${{ secrets.SFDX_AUTH_URL }} | sf org login sfdx-url -s -u -

      - name: 'Generate metadata delta pull request'
        run: |
          mkdir .temp
          sf sgd source delta --to "HEAD" --from "HEAD^" --output .temp/ --generate-delta

      - name: 'Run Apex tests'
        run: sf apex run test --test-level RunLocalTests --wait 30 --result-format human

      - name: 'Déployer les métadonnées sur la branch main'
        if: github.ref == 'refs/heads/main'
        run: sf project deploy start --manifest .temp/package/package.xml --test-level RunLocalTests --wait 30